Document: openni2
Title: Debian openni2 Manual
Author: <insert document author here>
Abstract: This manual describes what openni2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openni2/openni2.sgml.gz

Format: postscript
Files: /usr/share/doc/openni2/openni2.ps.gz

Format: text
Files: /usr/share/doc/openni2/openni2.text.gz

Format: HTML
Index: /usr/share/doc/openni2/html/index.html
Files: /usr/share/doc/openni2/html/*.html
